
FROM node:20-alpine

WORKDIR /app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Expone el puerto y ejecuta el servidor de desarrollo
EXPOSE 3000
CMD ["npm", "run", "dev"]
