
FROM node:20-alpine

WORKDIR /app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Construye la app y ejecuta en modo producción
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]
