"""add credentials and is_active to importer_configs

Revision ID: a4e1a42328f3
Revises: 6739f918fc74
Create Date: 2025-10-15 22:20:38.556331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e1a42328f3'
down_revision = '6739f918fc74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('importer_configs', sa.Column('credentials', sa.JSON(), nullable=True))
    # Add is_active with a server_default so existing rows get a value
    op.add_column('importer_configs', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('importer_configs', 'is_active')
    op.drop_column('importer_configs', 'credentials')
    # ### end Alembic commands ###
