"""add_categories_table

Revision ID: 208b3d5c51bf
Revises: 8065edb3e7aa
Create Date: 2025-10-09 04:04:50.139630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208b3d5c51bf'
down_revision: Union[str, Sequence[str], None] = '8065edb3e7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importer_name', sa.String(), nullable=False),
    sa.Column('category_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url_param', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_importer_name_unique', 'categories', ['importer_name', 'category_type', 'name'], unique=True)
    op.create_index('idx_importer_type', 'categories', ['importer_name', 'category_type'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_importer_name'), 'categories', ['importer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_importer_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_importer_type', table_name='categories')
    op.drop_index('idx_importer_name_unique', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
