"""add_importer_configs_table

Revision ID: 8065edb3e7aa
Revises: 7365629bd845
Create Date: 2025-10-08 20:05:55.379714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8065edb3e7aa'
down_revision: Union[str, Sequence[str], None] = '7365629bd845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importer_configs',
    sa.Column('importer_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config_fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('importer_name')
    )
    op.create_index(op.f('ix_importer_configs_importer_name'), 'importer_configs', ['importer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_importer_configs_importer_name'), table_name='importer_configs')
    op.drop_table('importer_configs')
    # ### end Alembic commands ###
